<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class Anthropic
{
    public const PROVIDER = 'Anthropic';

    public static function GenModel_3_7_sonnet_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-7-sonnet-latest',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
        );
    }

    public static function GenModel_3_7_sonnet_20250219(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-7-sonnet-20250219',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
        );
    }

    public static function GenModel_4_0_sonnet_20250514(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-sonnet-4-20250514',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
        );
    }

    public static function GenModel_4_5_sonnet_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-sonnet-4-5',
            description: 'Our smartest model for complex agents and coding',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_5_sonnet_20250929(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-sonnet-4-5-20250929',
            description: 'Our smartest model for complex agents and coding',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_6_sonnet_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-sonnet-4-6',
            description: 'The best combination of speed and intelligence',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_5_0_sonnet_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-sonnet-5',
            description: 'Near-Opus quality on coding and agentic work',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_5_5_sonnet_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-sonnet-5-5',
            description: 'Speed and capability for everyday coding, agent, and enterprise work',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_3_5_sonnet_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-5-sonnet-latest',
        );
    }

    public static function GenModel_3_5_sonnet_20241022(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-5-sonnet-20241022',
        );
    }

    public static function GenModel_3_5_sonnet_20240620(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-5-sonnet-20240620',
        );
    }

    public static function GenModel_4_5_haiku_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-haiku-4-5',
            description: 'Our fastest model with near-frontier intelligence',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_5_haiku_20251001(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-haiku-4-5-20251001',
            description: 'Our fastest model with near-frontier intelligence',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_3_5_haiku_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-5-haiku-latest',
        );
    }

    public static function GenModel_3_5_haiku_20241022(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-3-5-haiku-20241022',
        );
    }

    public static function GenModel_4_0_opus_20250514(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-20250514',
        );
    }

    public static function GenModel_4_1_opus_20250805(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-1-20250805',
            description: 'Exceptional model for specialized reasoning tasks',
            inputMaxToken: 200000,
            outputMaxToken: 32000,
        );
    }

    public static function GenModel_4_5_opus_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-5',
            description: 'Premium model combining maximum intelligence with practical performance',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_5_opus_20251101(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-5-20251101',
            description: 'Premium model combining maximum intelligence with practical performance',
            inputMaxToken: 200000,
            outputMaxToken: 64000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_6_opus_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-6',
            description: 'The most intelligent model for building agents and coding',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_7_opus_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-7',
            description: 'The most intelligent model for building agents and coding',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_4_8_opus_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-4-8',
            description: 'The most intelligent model for building agents and coding',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_5_0_opus_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-5',
            description: 'For complex agentic coding and enterprise work',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_5_5_opus_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-opus-5-5',
            description: 'Long-running agentic coding and knowledge work',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_5_0_fable_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-fable-5',
            description: 'Most capable tier for the most demanding reasoning and long-horizon agentic work',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    public static function GenModel_5_1_fable_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'claude-fable-5-1',
            description: 'Most capable tier for the most demanding reasoning and long-horizon agentic work',
            inputMaxToken: 1000000,
            outputMaxToken: 128000,
            supportTools: true,
            supportStructuredOutput: true,
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_3_7_sonnet_latest(),
            self::GenModel_3_7_sonnet_20250219(),
            self::GenModel_4_0_sonnet_20250514(),
            self::GenModel_4_5_sonnet_latest(),
            self::GenModel_4_5_sonnet_20250929(),
            self::GenModel_4_6_sonnet_latest(),
            self::GenModel_5_0_sonnet_latest(),
            self::GenModel_5_5_sonnet_latest(),
            self::GenModel_3_5_sonnet_latest(),
            self::GenModel_3_5_sonnet_20241022(),
            self::GenModel_3_5_sonnet_20240620(),
            self::GenModel_4_5_haiku_latest(),
            self::GenModel_4_5_haiku_20251001(),
            self::GenModel_3_5_haiku_latest(),
            self::GenModel_3_5_haiku_20241022(),
            self::GenModel_4_0_opus_20250514(),
            self::GenModel_4_1_opus_20250805(),
            self::GenModel_4_5_opus_latest(),
            self::GenModel_4_5_opus_20251101(),
            self::GenModel_4_6_opus_latest(),
            self::GenModel_4_7_opus_latest(),
            self::GenModel_4_8_opus_latest(),
            self::GenModel_5_0_opus_latest(),
            self::GenModel_5_5_opus_latest(),
            self::GenModel_5_0_fable_latest(),
            self::GenModel_5_1_fable_latest(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [];
    }
}
