<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class Catalog
{
    /** @return array<string, GenModel> keyed by FQN, e.g. "OpenAI/gpt-4o" */
    public static function genModels(): array
    {
        $models = [];
        foreach ([
            ...Anthropic::genModels(),
            ...Fireworks::genModels(),
            ...OMLX::genModels(),
            ...Ollama::genModels(),
            ...OpenAI::genModels(),
            ...VLLM::genModels(),
            ...VertexAI::genModels(),
            ...VoyageAI::genModels(),
            ...XAI::genModels(),
        ] as $model) {
            $models[$model->fqn()] = $model;
        }
        return $models;
    }

    /** @return array<string, EmbedModel> keyed by FQN, e.g. "OpenAI/gpt-4o" */
    public static function embedModels(): array
    {
        $models = [];
        foreach ([
            ...Anthropic::embedModels(),
            ...Fireworks::embedModels(),
            ...OMLX::embedModels(),
            ...Ollama::embedModels(),
            ...OpenAI::embedModels(),
            ...VLLM::embedModels(),
            ...VertexAI::embedModels(),
            ...VoyageAI::embedModels(),
            ...XAI::embedModels(),
        ] as $model) {
            $models[$model->fqn()] = $model;
        }
        return $models;
    }

    /** Looks up a known gen model by FQN, e.g. "Anthropic/claude-sonnet-4-5". */
    public static function gen(string $fqn): ?GenModel
    {
        return self::genModels()[$fqn] ?? null;
    }

    /** Looks up a known embed model by FQN, e.g. "VoyageAI/voyage-3.5". */
    public static function embed(string $fqn): ?EmbedModel
    {
        return self::embedModels()[$fqn] ?? null;
    }
}
