<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class Fireworks
{
    public const PROVIDER = 'Fireworks';

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [];
    }
}
