<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class Ollama
{
    public const PROVIDER = 'Ollama';

    public static function GenModel_llama_3_3(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.3',
            description: 'New state of the art 70B model. Llama 3.3 70B offers similar performance compared to Llama 3.1 405B model.',
        );
    }

    public static function GenModel_llama_3_2_vision_11b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.2-vision:11b',
            description: 'Llama 3.2 Vision is a collection of instruction-tuned image reasoning generative models in 11B sizes.',
        );
    }

    public static function GenModel_llama_3_2_vision_90b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.2-vision:90b',
            description: 'Llama 3.2 Vision is a collection of instruction-tuned image reasoning generative models in 90B sizes.',
        );
    }

    public static function GenModel_llama_3_2(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.2',
            description: 'Meta\'s Llama 3.2 goes small with 3B models. alias for llama3.2:3b',
        );
    }

    public static function GenModel_llama_3_2_3b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.2:3b',
            description: 'Meta\'s Llama 3.2 goes small with 3B models.',
        );
    }

    public static function GenModel_llama_3_2_1b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.2:1b',
            description: 'Meta\'s Llama 3.2 goes small with 1B models.',
        );
    }

    public static function GenModel_llama_3_1_8b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.1:8b',
            description: 'Llama 3.1 is a new state-of-the-art model from Meta available in 8Bparameter sizes.',
        );
    }

    public static function GenModel_llama_3_1_70b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.1:70b',
            description: 'Llama 3.1 is a new state-of-the-art model from Meta available in 70B parameter sizes.',
        );
    }

    public static function GenModel_llama_3_1_405b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'llama3.1:405b',
            description: 'Llama 3.1 is a new state-of-the-art model from Meta available in 405B parameter sizes.',
        );
    }

    public static function GenModel_gemma2(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemma2',
            description: 'Google Gemma 2 is a high-performing and efficient model available in three sizes: 9B',
        );
    }

    public static function GenModel_gemma2_9b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemma2:9b',
            description: 'Google Gemma 2 is a high-performing and efficient model available in three sizes: 2B, 9B, and 27B.',
        );
    }

    public static function GenModel_gemma2_2b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemma2:2b',
            description: 'Google Gemma 2 is a high-performing and efficient model available in three sizes: 2B, 9B, and 27B.',
        );
    }

    public static function GenModel_gemma2_27b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemma2:27b',
            description: 'Google Gemma 2 is a high-performing and efficient model available in three sizes: 2B, 9B, and 27B.',
        );
    }

    public static function GenModel_glm_4_7_flash_q4(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'glm-4.7-flash:q4_K_M',
        );
    }

    public static function EmbedModel_nomic_embed_text(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'nomic-embed-text',
            description: 'Most capable embedding Model for both english and non-english tasks, https://huggingface.co/nomic-ai/nomic-embed-text-v1.5',
            inputMaxTokens: 2048,
            outputDimensions: 768,
        );
    }

    public static function EmbedModel_mxbai_embed_large(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'mxbai-embed-large',
            description: 'State-of-the-art large embedding model from mixedbread.ai, https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1',
            inputMaxTokens: 512,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_paraphrase_multilingual(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'paraphrase-multilingual',
            description: 'Sentence-transformers model that can be used for tasks like clustering or semantic search., https://ollama.com/library/paraphrase-multilingual',
            inputMaxTokens: 512,
            outputDimensions: 768,
        );
    }

    public static function EmbedModel_bge_large(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'bge-large',
            description: 'Embedding model from BAAI mapping texts to vectors, https://ollama.com/library/bge-large',
            inputMaxTokens: 512,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_bge_m3(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'bge-m3',
            description: 'GE-M3 is a new model from BAAI distinguished for its versatility in Multi-Functionality, Multi-Linguality, and Multi-Granularity. https://ollama.com/library/bge-m3',
            inputMaxTokens: 8192,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_qwen_3_8b(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'qwen3-embedding:8b',
            inputMaxTokens: 32768,
            outputDimensions: 4096,
        );
    }

    public static function EmbedModel_qwen_3_06b(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'qwen3-embedding:0.6b',
            inputMaxTokens: 32768,
            outputDimensions: 4096,
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_llama_3_3(),
            self::GenModel_llama_3_2_vision_11b(),
            self::GenModel_llama_3_2_vision_90b(),
            self::GenModel_llama_3_2(),
            self::GenModel_llama_3_2_3b(),
            self::GenModel_llama_3_2_1b(),
            self::GenModel_llama_3_1_8b(),
            self::GenModel_llama_3_1_70b(),
            self::GenModel_llama_3_1_405b(),
            self::GenModel_gemma2(),
            self::GenModel_gemma2_9b(),
            self::GenModel_gemma2_2b(),
            self::GenModel_gemma2_27b(),
            self::GenModel_glm_4_7_flash_q4(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [
            self::EmbedModel_nomic_embed_text(),
            self::EmbedModel_mxbai_embed_large(),
            self::EmbedModel_paraphrase_multilingual(),
            self::EmbedModel_bge_large(),
            self::EmbedModel_bge_m3(),
            self::EmbedModel_qwen_3_8b(),
            self::EmbedModel_qwen_3_06b(),
        ];
    }
}
