<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class OMLX
{
    public const PROVIDER = 'oMLX';

    public static function GenModel_gemma4_26b_a4b_it_5bit(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'mlx-community/gemma-4-26b-a4b-it-5bit',
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_gemma4_26b_a4b_it_5bit(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [];
    }
}
