<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class OpenAI
{
    public const PROVIDER = 'OpenAI';

    public static function GenModel_gpt6_1_sol_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-6.1-sol',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt6_astra_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-6-astra',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt6_sol_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-6-sol',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt6_luna_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-6-luna',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_6_sol_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.6-sol',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_6_terra_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.6-terra',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_6_luna_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.6-luna',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_5_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.5',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_5_pro_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.5-pro',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_4_pro_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.4-pro',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_4_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.4',
            inputMaxToken: 1050000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_4_mini_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.4-mini',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_4_nano_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.4-nano',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_3_codex_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.3-codex',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_2_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.2',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_2_pro_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.2-pro',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_2_codex_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.2-codex',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_1_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.1',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_1_codex_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.1-codex',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_1_codex_max_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.1-codex-max',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_1_codex_mini_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5.1-codex-mini',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_pro_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5-pro',
            inputMaxToken: 400000,
            outputMaxToken: 272000,
        );
    }

    public static function GenModel_gpt5_codex_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5-codex',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_mini_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5-mini',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt5_nano_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-5-nano',
            inputMaxToken: 400000,
            outputMaxToken: 128000,
        );
    }

    public static function GenModel_gpt4_1_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4.1',
            inputMaxToken: 1047576,
            outputMaxToken: 32768,
        );
    }

    public static function GenModel_gpt4_1_250414(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4.1-2025-04-14',
            inputMaxToken: 1047576,
            outputMaxToken: 32768,
        );
    }

    public static function GenModel_gpt4_1_mini_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4.1-mini',
            inputMaxToken: 1047576,
            outputMaxToken: 32768,
        );
    }

    public static function GenModel_gpt4_1_mini_250414(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4.1-mini-2025-04-14',
            inputMaxToken: 1047576,
            outputMaxToken: 32768,
        );
    }

    public static function GenModel_gpt4_1_nano_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4.1-nano',
            inputMaxToken: 1047576,
            outputMaxToken: 32768,
        );
    }

    public static function GenModel_gpt4_1_nano_250414(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4.1-nano-2025-04-14',
            inputMaxToken: 1047576,
            outputMaxToken: 32768,
        );
    }

    public static function GenModel_gpt4o_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'chatgpt-4o-latest',
            description: 'Our high-intelligence flagship Model for complex, multi-step tasks. GPT-4o is cheaper and faster than GPT-4 Turbo.',
        );
    }

    public static function GenModel_gpt4o(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4o',
            description: 'Our high-intelligence flagship Model for complex, multi-step tasks. GPT-4o is cheaper and faster than GPT-4 Turbo.',
        );
    }

    public static function GenModel_gpt4o_240806(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4o-2024-08-06',
            description: 'Our high-intelligence flagship Model for complex, multi-step tasks. GPT-4o is cheaper and faster than GPT-4 Turbo.',
        );
    }

    public static function GenModel_gpt4o_240513(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4o-2024-05-13',
            description: 'Our high-intelligence flagship Model for complex, multi-step tasks. GPT-4o is cheaper and faster than GPT-4 Turbo.',
        );
    }

    public static function GenModel_gpt4o_mini(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4o-mini',
            description: 'Our affordable and intelligent small Model for fast, lightweight tasks. GPT-4o mini is cheaper and more capable,than GPT-3.5 Turbo.',
        );
    }

    public static function GenModel_gpt4o_mini_240718(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4o-mini-2024-07-18',
            description: 'Our affordable and intelligent small Model for fast, lightweight tasks. GPT-4o mini is cheaper and more capable,than GPT-3.5 Turbo.',
        );
    }

    public static function GenModel_o1_preview(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o1-preview',
            description: 'The o1 series of large language models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user.',
        );
    }

    public static function GenModel_o1_preview_240912(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o1-preview-2024-09-12',
            description: 'The o1 series of large language models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user.',
        );
    }

    public static function GenModel_o1_mini(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o1-mini',
            description: 'The o1 series of large language models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user.',
        );
    }

    public static function GenModel_o1_mini_240912(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o1-mini-2024-09-12',
            description: 'The o1 series of large language models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user.',
        );
    }

    public static function GenModel_o4_mini_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o4-mini',
            inputMaxToken: 200000,
            outputMaxToken: 100000,
        );
    }

    public static function GenModel_o3_pro_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o3-pro',
            inputMaxToken: 200000,
            outputMaxToken: 100000,
        );
    }

    public static function GenModel_o3_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o3',
            inputMaxToken: 200000,
            outputMaxToken: 100000,
        );
    }

    public static function GenModel_o4_mini_250416(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o4-mini-2025-04-16',
        );
    }

    public static function GenModel_o3_pro_250610(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o3-pro-2025-06-10',
        );
    }

    public static function GenModel_o3_250416(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o3-2025-04-16',
        );
    }

    public static function GenModel_o3_mini_250131(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'o3-mini-2025-01-31',
        );
    }

    public static function GenModel_gpt4_turbo(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4-turbo',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function GenModel_gpt4_turbo_240409(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4-turbo-2024-04-09',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function GenModel_gpt4_turbo_preview(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4-turbo-preview',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function GenModel_gpt4_preview_0125(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4-0125-preview',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function GenModel_gpt4_preview_1106(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4-1106-preview',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function GenModel_gpt4(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function GenModel_gpt4_0613(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gpt-4-0613',
            description: 'GPT-4 is a large multimodal Model (accepting text or image inputs and outputting text) that can solve difficult problems with greater accuracy than any of our previous models, thanks to its broader general knowledge and advanced reasoning capabilities. GPT-4 is available in the OpenAI API to paying customers. Like gpt-3.5-turbo, GPT-4 is optimized for chat but works well for traditional completions tasks using the Chat Completions API. Learn how to use GPT-4 in our text generation guide.',
        );
    }

    public static function EmbedModel_text3_small(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'text-embedding-3-small',
            description: 'Small, cost-efficient third-generation embedding model with increased performance over text-embedding-ada-002; supports shortening the output dimensions',
            inputMaxTokens: 8191,
            outputDimensions: 1536,
        );
    }

    public static function EmbedModel_text3_large(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'text-embedding-3-large',
            description: 'Most capable embedding model for both English and non-English tasks; supports shortening the output dimensions',
            inputMaxTokens: 8191,
            outputDimensions: 3072,
        );
    }

    public static function EmbedModel_text_ada_002(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'text-embedding-ada-002',
            description: 'Legacy second-generation embedding model; prefer text-embedding-3-small or text-embedding-3-large',
            inputMaxTokens: 8191,
            outputDimensions: 1536,
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_gpt6_1_sol_latest(),
            self::GenModel_gpt6_astra_latest(),
            self::GenModel_gpt6_sol_latest(),
            self::GenModel_gpt6_luna_latest(),
            self::GenModel_gpt5_6_sol_latest(),
            self::GenModel_gpt5_6_terra_latest(),
            self::GenModel_gpt5_6_luna_latest(),
            self::GenModel_gpt5_5_latest(),
            self::GenModel_gpt5_5_pro_latest(),
            self::GenModel_gpt5_4_pro_latest(),
            self::GenModel_gpt5_4_latest(),
            self::GenModel_gpt5_4_mini_latest(),
            self::GenModel_gpt5_4_nano_latest(),
            self::GenModel_gpt5_3_codex_latest(),
            self::GenModel_gpt5_2_latest(),
            self::GenModel_gpt5_2_pro_latest(),
            self::GenModel_gpt5_2_codex_latest(),
            self::GenModel_gpt5_1_latest(),
            self::GenModel_gpt5_1_codex_latest(),
            self::GenModel_gpt5_1_codex_max_latest(),
            self::GenModel_gpt5_1_codex_mini_latest(),
            self::GenModel_gpt5_latest(),
            self::GenModel_gpt5_pro_latest(),
            self::GenModel_gpt5_codex_latest(),
            self::GenModel_gpt5_mini_latest(),
            self::GenModel_gpt5_nano_latest(),
            self::GenModel_gpt4_1_latest(),
            self::GenModel_gpt4_1_250414(),
            self::GenModel_gpt4_1_mini_latest(),
            self::GenModel_gpt4_1_mini_250414(),
            self::GenModel_gpt4_1_nano_latest(),
            self::GenModel_gpt4_1_nano_250414(),
            self::GenModel_gpt4o_latest(),
            self::GenModel_gpt4o(),
            self::GenModel_gpt4o_240806(),
            self::GenModel_gpt4o_240513(),
            self::GenModel_gpt4o_mini(),
            self::GenModel_gpt4o_mini_240718(),
            self::GenModel_o1_preview(),
            self::GenModel_o1_preview_240912(),
            self::GenModel_o1_mini(),
            self::GenModel_o1_mini_240912(),
            self::GenModel_o4_mini_latest(),
            self::GenModel_o3_pro_latest(),
            self::GenModel_o3_latest(),
            self::GenModel_o4_mini_250416(),
            self::GenModel_o3_pro_250610(),
            self::GenModel_o3_250416(),
            self::GenModel_o3_mini_250131(),
            self::GenModel_gpt4_turbo(),
            self::GenModel_gpt4_turbo_240409(),
            self::GenModel_gpt4_turbo_preview(),
            self::GenModel_gpt4_preview_0125(),
            self::GenModel_gpt4_preview_1106(),
            self::GenModel_gpt4(),
            self::GenModel_gpt4_0613(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [
            self::EmbedModel_text3_small(),
            self::EmbedModel_text3_large(),
            self::EmbedModel_text_ada_002(),
        ];
    }
}
