<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class VertexAI
{
    public const PROVIDER = 'VertexAI';

    // Provider specific embedding types, use with EmbedModel::withType().
    public const TypeDocument = 'RETRIEVAL_DOCUMENT';
    public const TypeQuery = 'RETRIEVAL_QUERY';
    public const TypeQuestionAnswer = 'QUESTION_ANSWERING';
    public const TypeFactVerification = 'FACT_VERIFICATION';
    public const TypeCodeRetrieval = 'CODE_RETRIEVAL_QUERY';
    public const TypeClustering = 'CLUSTERING';
    public const TypeClassification = 'CLASSIFICATION';
    public const TypeSemanticSimilarity = 'SEMANTIC_SIMILARITY';

    public static function GenModel_gemini_3_8_flash_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.8-flash',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_7_flash_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.7-flash',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_6_flash_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.6-flash',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_5_flash_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.5-flash',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_5_flash_lite_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.5-flash-lite',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_1_flash_lite_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.1-flash-lite',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_2_5_pro_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-2.5-pro',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_2_5_flash_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-2.5-flash',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_2_5_flash_lite_latest(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-2.5-flash-lite',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_pro_preview(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3-pro-preview',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_1_pro_preview(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.1-pro-preview',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_flash_preview(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3-flash-preview',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function GenModel_gemini_3_1_flash_lite_preview(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'gemini-3.1-flash-lite-preview',
            inputMaxToken: 1048576,
            outputMaxToken: 65536,
        );
    }

    public static function EmbedModel_gemini_001(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'gemini-embedding-001',
            description: 'State-of-the-art performance across English, multilingual and code tasks. It unifies the previously specialized models like text-embedding-005 and text-multilingual-embedding-002 and achieves better performance in their respective domains.',
            inputMaxTokens: 2048,
            outputDimensions: 3072,
        );
    }

    public static function EmbedModel_text_005(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'text-embedding-005',
            description: 'see https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/text-embeddings-api',
            inputMaxTokens: 2048,
            outputDimensions: 768,
        );
    }

    public static function EmbedModel_text_004(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'text-embedding-004',
            description: 'see https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/text-embeddings-api',
            inputMaxTokens: 2048,
            outputDimensions: 768,
        );
    }

    public static function EmbedMode_multilang_002(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'text-multilingual-embedding-002',
            description: 'see https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/text-embeddings-api',
            inputMaxTokens: 2048,
            outputDimensions: 768,
        );
    }

    public static function EmbedModel_text_gecko_003(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'textembedding-gecko@003',
            description: 'see https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/text-embeddings-api',
            inputMaxTokens: 2048,
            outputDimensions: 768,
        );
    }

    public static function EmbedModel_text_gecko_multilang_001(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'textembedding-gecko-multilingual@001',
            description: 'see https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/text-embeddings-api',
            inputMaxTokens: 2048,
            outputDimensions: 768,
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_gemini_3_8_flash_latest(),
            self::GenModel_gemini_3_7_flash_latest(),
            self::GenModel_gemini_3_6_flash_latest(),
            self::GenModel_gemini_3_5_flash_latest(),
            self::GenModel_gemini_3_5_flash_lite_latest(),
            self::GenModel_gemini_3_1_flash_lite_latest(),
            self::GenModel_gemini_2_5_pro_latest(),
            self::GenModel_gemini_2_5_flash_latest(),
            self::GenModel_gemini_2_5_flash_lite_latest(),
            self::GenModel_gemini_3_pro_preview(),
            self::GenModel_gemini_3_1_pro_preview(),
            self::GenModel_gemini_3_flash_preview(),
            self::GenModel_gemini_3_1_flash_lite_preview(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [
            self::EmbedModel_gemini_001(),
            self::EmbedModel_text_005(),
            self::EmbedModel_text_004(),
            self::EmbedMode_multilang_002(),
            self::EmbedModel_text_gecko_003(),
            self::EmbedModel_text_gecko_multilang_001(),
        ];
    }
}
