<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class VLLM
{
    public const PROVIDER = 'vLLM';

    public static function EmbedModel_qwen_3_8b(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'Qwen/Qwen3-Embedding-8B',
            inputMaxTokens: 32768,
            outputDimensions: 4096,
        );
    }

    public static function EmbedModel_qwen_3_4b(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'Qwen/Qwen3-Embedding-4B',
            inputMaxTokens: 32768,
            outputDimensions: 2560,
        );
    }

    public static function GenModel_gpt_oss_20b(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'openai/gpt-oss-20b',
        );
    }

    public static function GenModel_gemma_4_e4b_it(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'google/gemma-4-E4B-it',
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_gpt_oss_20b(),
            self::GenModel_gemma_4_e4b_it(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [
            self::EmbedModel_qwen_3_8b(),
            self::EmbedModel_qwen_3_4b(),
        ];
    }
}
