<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class VoyageAI
{
    public const PROVIDER = 'VoyageAI';

    // Provider specific embedding types, use with EmbedModel::withType().
    public const TypeQuery = 'Represent the query for retrieving supporting documents';
    public const TypeDocument = 'Represent the document for retrieval';

    public static function EmbedModel_voyage_context_4(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-context-4',
            description: 'Contextualized chunk embeddings, used with EmbedDocument. Successor of voyage-context-3 with higher retrieval quality; 32k tokens per chunk, 120k tokens per document.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_context_3(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-context-3',
            description: 'Used for contextualized embeddings and used with EmbedDocument',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_3_5(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-3.5',
            description: 'Optimized for general-purpose and multilingual retrieval quality.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_3_5_lite(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-3.5-lite',
            description: 'Optimized for latency and cost.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_3_large(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-3-large',
            description: 'The best general-purpose and multilingual retrieval quality',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_3(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-3',
            description: 'Optimized for general-purpose and multilingual retrieval quality.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_3_lite(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-3-lite',
            description: 'Optimized for latency and cost',
            inputMaxTokens: 32000,
            outputDimensions: 512,
        );
    }

    public static function EmbedModel_voyage_4_large(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-4-large',
            description: 'The best general-purpose and multilingual retrieval quality',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_4(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-4',
            description: 'Optimized for general-purpose and multilingual retrieval quality.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_4_lite(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-4-lite',
            description: 'Optimized for latency and cost',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_finance_2(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-finance-2',
            description: 'Optimized for finance retrieval and RAG.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_multilingual_2(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-multilingual-2',
            description: 'Optimized for multilingual retrieval and RAG.',
            inputMaxTokens: 32000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_law_2(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-law-2',
            description: 'Optimized for legal and long-context retrieval and RAG. Also improved performance across all domains.',
            inputMaxTokens: 16000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_code_2(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-code-2',
            description: 'Optimized for code retrieval (17% better than alternatives)',
            inputMaxTokens: 16000,
            outputDimensions: 1536,
        );
    }

    public static function EmbedModel_voyage_large_2_instruct(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-large-2-instruct',
            description: 'Top of MTEB leaderboard . Instruction-tuned general-purpose embedding model optimized for clustering, classification, and retrieval. For retrieval, please use input_type parameter to specify whether the text is a query or document. For classification and clustering, please use the instructions here . See blog post for details. We recommend existing voyage-large-2-instruct users to transition to voyage-3',
            inputMaxTokens: 16000,
            outputDimensions: 1024,
        );
    }

    public static function EmbedModel_voyage_large_2(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-large-2',
            description: 'General-purpose embedding model that is optimized for retrieval quality (e.g., better than OpenAI V3 Large). Please transition to voyage-3.',
            inputMaxTokens: 16000,
            outputDimensions: 1536,
        );
    }

    public static function EmbedModel_voyage_2(): EmbedModel
    {
        return new EmbedModel(
            provider: self::PROVIDER,
            name: 'voyage-2',
            description: 'General-purpose embedding model optimized for a balance between cost, latency, and retrieval quality. Please transition to voyage-3-lite.',
            inputMaxTokens: 4000,
            outputDimensions: 1024,
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [
            self::EmbedModel_voyage_context_4(),
            self::EmbedModel_voyage_context_3(),
            self::EmbedModel_voyage_3_5(),
            self::EmbedModel_voyage_3_5_lite(),
            self::EmbedModel_voyage_3_large(),
            self::EmbedModel_voyage_3(),
            self::EmbedModel_voyage_3_lite(),
            self::EmbedModel_voyage_4_large(),
            self::EmbedModel_voyage_4(),
            self::EmbedModel_voyage_4_lite(),
            self::EmbedModel_voyage_finance_2(),
            self::EmbedModel_voyage_multilingual_2(),
            self::EmbedModel_voyage_law_2(),
            self::EmbedModel_voyage_code_2(),
            self::EmbedModel_voyage_large_2_instruct(),
            self::EmbedModel_voyage_large_2(),
            self::EmbedModel_voyage_2(),
        ];
    }
}
