<?php

// Code generated by modelgen from the bellman Go library. DO NOT EDIT.

declare(strict_types=1);

namespace Bellman\Models;

use Bellman\Embed\Model as EmbedModel;
use Bellman\Gen\Model as GenModel;

final class XAI
{
    public const PROVIDER = 'xAI';

    public static function GenModel_grok_4_20_reasoning(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'grok-4.20-reasoning',
            usesAdaptiveThinking: true,
        );
    }

    public static function GenModel_grok_4_20_multi_agent(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'grok-4.20-multi-agent',
            usesAdaptiveThinking: true,
        );
    }

    public static function GenModel_grok_4_1_fast_reasoning(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'grok-4-1-fast-reasoning',
            usesAdaptiveThinking: true,
        );
    }

    public static function GenModel_grok_4(): GenModel
    {
        return new GenModel(
            provider: self::PROVIDER,
            name: 'grok-4',
        );
    }

    /** @return list<GenModel> */
    public static function genModels(): array
    {
        return [
            self::GenModel_grok_4_20_reasoning(),
            self::GenModel_grok_4_20_multi_agent(),
            self::GenModel_grok_4_1_fast_reasoning(),
            self::GenModel_grok_4(),
        ];
    }

    /** @return list<EmbedModel> */
    public static function embedModels(): array
    {
        return [];
    }
}
